spring.application.name=lb1
spring.datasource.url=jdbc:postgresql://localhost:5432/LabWork
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.oauth2.client=DEBUG



# OAuth2 Client Registration for Keycloak
spring.security.oauth2.client.registration.keycloak.client-id=IS-client
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8080/login/oauth2/code/keycloak
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8180/realms/IS-realm/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:8180/realms/IS-realm/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://localhost:8180/realms/IS-realm/protocol/openid-connect/certs

spring.security.oauth2.client.provider.keycloak.logout-uri=http://localhost:8180/realms/IS-realm/protocol/openid-connect/logout


keycloak.auth-server-url=http://localhost:8180
keycloak.realm="IS-realm"
keycloak.resource=IS-admin
keycloak.credentials.secret=${KEYCLOAK_CREDENTIALS_SECRET}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD}
keycloak.bearer-only=false
keycloak.public-client=true
keycloak.use-resource-role-mappings=true
keycloak.ssl-required=external

spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

server.tomcat.max-swallow-size=2GB
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=30000



